version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test123
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin3306
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: